version: '2'

services:
  ngal:
    build: .
    container_name: ngal
    command: bash -c "python3 setup.py develop && mkdir -p notebooks && cd notebooks && jupyter notebook --ip=127.0.0.1 --allow-root"
    volumes:
      - .:/naminggamesal
    ports:
      - "8888:8888"
